### ISSUE TITLE
Preprocessed avatarrex dataset misses smpl_params.npz

### ISSUE THREAD

**Issue by xiao10ma** [lizhe00/AnimatableGaussians#30]
I use the link https://github.com/lizhe00/AnimatableGaussians/blob/master/PREPROCESSED_DATASET.md to download the preprocessed avatarrex data. However, the error report reminds me that it lacks the smpl_params.npz.

```
(m3dgs) (base) duantong@user-R8428-A12:/data/duantong/mazipei/AnimatableGaussians$ python main_avatar.py -c configs/avatarrex_zzr/avatar.yaml --mode=train
# Using Pytorch3d Renderer
Import AvatarNet from network.avatar
# Parameter number of AvatarNet is 223648936
Traceback (most recent call last):
  File "main_avatar.py", line 834, in <module>
    trainer.pretrain()
  File "main_avatar.py", line 269, in pretrain
    self.dataset = MvRgbDataset(**self.opt['train']['data'])
  File "/data/duantong/mazipei/AnimatableGaussians/dataset/dataset_mv_rgb.py", line 393, in __init__
    super(MvRgbDatasetAvatarReX, self).__init__(
  File "/home/duantong/anaconda3/envs/m3dgs/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/duantong/mazipei/AnimatableGaussians/dataset/dataset_mv_rgb.py", line 40, in __init__
    self.load_smpl_data()
  File "/data/duantong/mazipei/AnimatableGaussians/dataset/dataset_mv_rgb.py", line 253, in load_smpl_data
    smpl_data = np.load(self.data_dir + '/smpl_params.npz', allow_pickle = True)
  File "/home/duantong/anaconda3/envs/m3dgs/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './avatar_data/avatarrex/zzr/smpl_params.npz'
```

**Comment by lizhe00** [comment]
You should also download the original data from https://github.com/lizhe00/AnimatableGaussians/blob/master/AVATARREX_DATASET.md.

**Comment by xiao10ma** [comment]
ok, thanks!

**Comment by xiao10ma** [comment]
> You should also download the original data from https://github.com/lizhe00/AnimatableGaussians/blob/master/AVATARREX_DATASET.md.

ok, thanks!
