### ISSUE TITLE
ValueError: Invalid data_path!

### ISSUE THREAD

**Issue by shuodehaoa** [lizhe00/AnimatableGaussians#32]
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "/nas/project/AnimatableGaussians/main_avatar.py", line 837, in <module>
    trainer.test()
  File "/home/gao/anaconda3/envs/AniGaussian/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/nas/project/AnimatableGaussians/main_avatar.py", line 535, in test
    testing_dataset = PoseDataset(**self.opt['test']['pose_data'], smpl_shape = training_dataset.smpl_data['betas'][0])
  File "/home/gao/anaconda3/envs/AniGaussian/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/nas/project/AnimatableGaussians/dataset/dataset_pose.py", line 59, in __init__
    raise ValueError('Invalid data_path!')
ValueError: Invalid data_path!

**Comment by shuodehaoa** [comment]
subject_name: avatarrex_lbn2
    data_dir: /nas/dataset/avatarrex_lbn2_data
    frame_range: *id001
  pose_data:
#    data_path: Z:/Data/Pose/thuman4/pose_00.npz
#    frame_range: [2000, 2500]
#    data_path: Z:/Data/Pose/AMASS/CMU/06/06_13_poses.npz
#    data_path: Z:/Data/Pose/AMASS/CMU/10/10_05_poses.npz
    data_path: /nas/dataset/ACCAD/ACCAD/Female1General_c3d/test.npz
    frame_interval: 4
  view_setting: front
  render_view_idx: 0
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  fix_hand: true
  fix_hand_id: 431
  n_pca: 20
  sigma_pca: 2.0
  prev_ckpt: ./results/avatarrex_lbn2/avatar/batch_800000
model:
  with_viewdirs: true
  random_style: false

**Comment by shuodehaoa** [comment]
`    subject_name: avatarrex_lbn2
    data_dir: /nas/dataset/avatarrex_lbn2_data
    frame_range: *id001
  pose_data:
#    data_path: Z:/Data/Pose/thuman4/pose_00.npz
#    frame_range: [2000, 2500]
#    data_path: Z:/Data/Pose/AMASS/CMU/06/06_13_poses.npz
#    data_path: Z:/Data/Pose/AMASS/CMU/10/10_05_poses.npz
    data_path: /nas/dataset/ACCAD/ACCAD/Female1General_c3d/test.npz
    frame_interval: 4
  view_setting: front
  render_view_idx: 0
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  fix_hand: true
  fix_hand_id: 431
  n_pca: 20
  sigma_pca: 2.0
  prev_ckpt: ./results/avatarrex_lbn2/avatar/batch_800000
model:
  with_viewdirs: true
  random_style: false`
  This is my avatar.yaml~

**Comment by shuodehaoa** [comment]
![image](https://github.com/lizhe00/AnimatableGaussians/assets/25994081/d91660e9-738f-49fe-88c5-0dc561112235)
This is my avatar.yaml file
running command is "python main_avatar.py -c configs/avatarrex_lbn2/avatar.yaml --mode=test"
Is there any problem? Please help me! I will appreciate

**Comment by fluide1022** [comment]
+1

**Comment by zhiyw120547** [comment]
you need put the test.npz under avatarrex_lbn2(together with image, mask ......)then this error will disappear
